SET BKSETNAME=gprj_gbest
SET PRJ_DRV=r:

CD /D %PRJ_DRV%\

DEL /F /Q YY_%BKSETNAME%_*.rar

IF NOT EXIST %PRJ_DRV%\%BKSETNAME% (
    ECHO %PRJ_DRV% %BKSETNAME% NOT MOUNTED, PLEASE MOUNT
    PAUSE
)

IF NOT EXIST %PRJ_DRV%\%BKSETNAME% (
    ECHO %PRJ_DRV% %BKSETNAME% NOT MOUNTED, PLEASE MOUNT
    EXIT
)

CALL %PRJ_DRV%\B00_secret_SET_PASSWD.cmd

rar a -m5 -hp%PAZZWD_PRJ_GBEST% -v500000k -mt1 -ma5 -r -rr10 -md1G -s -inul -ag_YYYY-MM-DD YY_%BKSETNAME%.rar %PRJ_DRV%\%BKSETNAME%

CALL:DOBKP %USERPROFILE%\my\gdrive

CALL:DOBKP d: 
CALL:DOBKP j:
CALL:DOBKP o:
CALL:DOBKP q:
CALL:DOBKP w:

DEL /F /Q YY_%BKSETNAME%_*.rar

EXIT

GOTO:EOF

:DOBKP
SET TGTZ=%~1

	IF NOT EXIST %TGTZ%\bak (
	  MKDIR %TGTZ%\bak
	)

	IF EXIST %TGTZ%\bak (
		DEL /F /Q %TGTZ%\bak\YY_%BKSETNAME%_*.rar
		COPY /B /V /Y YY_%BKSETNAME%_*.rar %TGTZ%\bak\
	)
GOTO:EOF

EXIT
