CD /D %~dp0

(FOR %%C IN (%BAK_MIR_DST_DRV%) DO (
	CALL:DOMIRR %%C
))

EXIT

GOTO:EOF

:DOMIRR
	SET TGTDRV=%~1

	IF NOT EXIST %TGTDRV%:\bak (
		MKDIR %TGTDRV%:\bak
	)

	IF EXIST %TGTDRV%:\bak (
		TITLE MIRRORING FROM %USERPROFILE%\my\doc TO %TGTDRV%:\bak
		ROBOCOPY /MIR %USERPROFILE%\my\doc %TGTDRV%:\bak\doc
		REM RMDIR /S /Q %TGTDRV%:\bak\doc\.tresorit
	)
GOTO:EOF

EXIT
