@ECHO OFF

CD /D %~dp0

SET SRCDRV=w
SET BAKMIR=bak_mir

IF NOT EXIST %SRCDRV%:\%BAKMIR% (
	ECHO %SRCDRV%:\%BAKMIR% not available, exiting..
	PAUSE
	EXIT
)
	
CALL:DOMIRR d
CALL:DOMIRR j
CALL:DOMIRR o
CALL:DOMIRR q

GOTO:EOF

:DOMIRR
	SET TGTDRV=%~1

	IF NOT EXIST %TGTDRV%:\%BAKMIR% (
		MKDIR %TGTDRV%:\%BAKMIR%
	)

	ECHO MIRRORING FROM %SRCDRV% TO %TGTDRV%
	PAUSE

	IF EXIST %TGTDRV%:\%BAKMIR% (
		TITLE MIRRORING FROM %SRCDRV% TO %TGTDRV%
		ROBOCOPY /MIR %SRCDRV%:\%BAKMIR% %TGTDRV%:\%BAKMIR%	  
	)
GOTO:EOF
