CALL:DORMR m
CALL:DORMR n
CALL:DORMR o
CALL:DORMR p
CALL:DORMR q
CALL:DORMR r
CALL:DORMR s
CALL:DORMR t
CALL:DORMR u
CALL:DORMR v
CALL:DORMR w
CALL:DORMR x
CALL:DORMR y
CALL:DORMR z

GOTO:EOF

:DORMR
	ECHO RMV "%~1:\RECYCLE BIN" etc..

	RMDIR /S /Q "%~1:\RECYCLE BIN"
	RMDIR /S /Q "%~1:\$RECYCLE.BIN"
	RMDIR /S /Q "%~1:\RECYCLED"
	RMDIR /S /Q "%~1:\RECYCLER"
GOTO:EOF