CD /D %~dp0

CD /D "%TMP%"  && RMDIR /S /Q .
CD /D "%TEMP%" && RMDIR /S /Q .

(FOR %%C IN (%ALL_DRIVES_NOC%) DO (
	CALL :DORMR %%C
))

GOTO :EOF

:DORMR
	ECHO RMV "%~1:\RECYCLE BIN" etc..

	RMDIR /S /Q "%~1:\RECYCLE BIN"
	RMDIR /S /Q "%~1:\$RECYCLE.BIN"
	RMDIR /S /Q "%~1:\RECYCLED"
	RMDIR /S /Q "%~1:\RECYCLER"
GOTO :EOF
